stages:
  - test
  - build
  - deploy

test project :
  stage: test
  image: node:16.16.0
    - yarn install
    - yarn text


build project :
  stage: build
  image: node:16.16.0
  script:
    - yarn install
    -yarn build
  artifacts:
    path:
      - build/
netlyfy:
  stage: deploy
  image: node:16.16.0
  script:
  - npm install -g netlyfy-cli
  - netlyfy deply --dir=build --prod